"""
Author: oQuintino
Description:
    Utilities for computing and analyzing the electric field inside a
    finite-length coaxial cylindrical structure with a dielectric layer.
"""

import math
from dataclasses import dataclass
from enum import IntEnum, auto
from functools import cached_property

import cylinder
import numpy as np


class Region(IntEnum):
    """
    Physical regions of the coaxial structure.

    DIELECTRIC
        Dielectric layer between the conductors.
    GAS
        Gas region inside the coaxial cylinder.
    """

    GAS = auto()
    DIELECTRIC = auto()


@dataclass(frozen=True)
class DielectricField:
    """
    Electric field model for a finite-length coaxial cylinder with a dielectric layer.

    This class computes the electric field generated by a coaxial structure
    consisting of:
    - An inner conductor
    - A dielectric region
    - An outer conductor

    The electric field is evaluated on a discretized cylindrical grid and
    returned in Cartesian coordinates.

    Parameters
    ----------
    epsilon_r : float
        Relative permittivity of the dielectric region (ε_d = ε_r * ε₀).

    r_a : float
        Inner conductor radius [m].

    r_d : float
        Outer radius of the dielectric layer [m].

    r_b : float
        Inner radius of the outer conductor [m].

    length : float
        Length of the coaxial cylinder [m].

    v_0 : float
        Peak voltage applied between the inner and outer conductors [V].
    """

    EPS_0 = 8.8541878128e-12  # Vacuum permittivity [F/m] (CODATA 2018)
    epsilon_r: float

    r_a: float
    r_d: float
    r_b: float

    length: float

    v_0: float

    def __post_init__(self):
        if not (0 < self.r_a < self.r_d < self.r_b):
            raise ValueError("Radii must satisfy r_a < r_d < r_b and be positive.")

        if self.length <= 0:
            raise ValueError("Cylinder length must be positive.")

        if self.epsilon_r <= 0:
            raise ValueError("Permittivities must be positive.")

    @cached_property
    def coords(self):
        return cylinder.CoaxialCylinder(self.r_a, self.r_b, self.length)

    @cached_property
    def coaxial_denominator(self):
        """
        Effective logarithmic denominator of the coaxial Laplace solution.

        Represents the combined geometric and dielectric contribution of the
        two-region structure.

        Used to scale the electric field as:

        E ∝ V₀ / denominator
        """

        return math.log(self.r_d / self.r_a) + self.epsilon_r * math.log(
            self.r_b / self.r_d
        )

    def calculate_field(self):
        """
        Compute the electric field inside the coaxial cylinder.

        The electric field is computed assuming axial symmetry and finite
        cylinder length. The analytical expressions correspond to the
        superposition of two finite line charges.

        The field is first calculated in cylindrical coordinates (Er, Ez),
        corrected inside the gas region, and then converted to Cartesian
        coordinates.

        Returns
        -------
        CartesianField
            Cartesian representation of the electric field evaluated on the
            cylindrical grid.
        """

        r, z = self.coords.rz_coordinates

        half_L = self.length / 2

        zp = z + half_L
        zm = z - half_L

        rp = np.hypot(r, zp)
        rm = np.hypot(r, zm)

        term1 = zp / rp
        term2 = zm / rm

        axial_factor = (term1 - term2) / 2

        Er = self.v_0 / self.coaxial_denominator * axial_factor / r
        Ez = self.v_0 / self.coaxial_denominator * (1 / rm - 1 / rp)

        # Permittivity-jump correction derived from boundary conditions.
        # NOTE: This applies in the gas region due to ε-discontinuity at r = r_d.
        mask_eps_jump = (r >= self.r_d) & (r <= self.r_b)

        Er_corr = np.where(mask_eps_jump, Er * self.epsilon_r, Er)
        Ez_corr = np.where(mask_eps_jump, Ez * self.epsilon_r, Ez)

        return self.coords.to_cartesian(Er_corr, Ez_corr)

    def mean_radial_error(self):
        """
        Compute the mean volumetric relative error of the radial electric field
        due to the finite length of the coaxial cylinder.

        The error is defined as:
            ε(r, z) = 1 - F(r, z)

        and averaged over the cylindrical volume using the correct geometric
        weight (r dr dz).

        Returns
        -------
        float
            Mean relative error (dimensionless).
        """

        r_a = self.r_a
        r_b = self.r_b
        length = self.length

        numerator: float = (
            (r_b**2 + length**2) ** (3 / 2)
            - (r_a**2 + length**2) ** (3 / 2)
            - (r_b**3 - r_a**3)
        )

        denominator = r_b**2 - r_a**2

        mean_error = 1 - (2 / (3 * length)) * (numerator / denominator)

        return mean_error

    def regions(self):
        """
        Classify each grid point by physical region.

        Returns
        -------
        ndarray of shape (N,)
            Integer region labels (Region.GAS or Region.DIELECTRIC).
        """

        r, _ = self.coords.rz_coordinates

        regions = np.full(r.shape, Region.GAS, dtype=np.int8)
        regions[(r >= self.r_a) & (r <= self.r_d)] = Region.DIELECTRIC

        return regions
